### PR TITLE
ci(storybook): fix turbo snap

### PR DESCRIPTION
**Pull request by ryanbas21**
fix turbo snap to run less snapshots and builds with chromatic

### CODE REVIEW

**Comment by ryanbas21** [comment]
Your preview environment [pr-80-ryanbas21](https://cloud.okteto.com/#/previews/pr-80-ryanbas21) has been deployed.

  Preview environment endpoint is available [here](https://preview-pr-80-ryanbas21.cloud.okteto.net)

**Review by cerebrl — APPROVED** [review]
I see there's a failed UI test, but that's fixed in a different PR. You can ignore that failure.

**Pull request merged**
